### ISSUE TITLE
Le nom de l'équipe ne s'affiche pas dans l'outil de recherche des cartes

### ISSUE THREAD

**Issue by C-Sophie** [umap-project/umap-dsfr#24]
Sur la [page de recherche de cartes](https://umap.incubateur.anct.gouv.fr/fr/search/), les cartes sont associées à leur auteur et non à l'équipe alors que la carte porte bien le nom de l'équipe. Il faudrait que le nom de l'équipe soit affiché aussi sur la page de recherche. 

**Affichage dans l'outil de recherche :** 
![Image](https://github.com/user-attachments/assets/f470bc31-00a5-4fa9-839a-6da602bbc5f7)
**Affichage sur la carte :** 
![Image](https://github.com/user-attachments/assets/737f913e-e0d8-4113-818f-cefb167aa356)

**Comment by davidbgk** [comment]
Note pour ne pas oublier : il est probable que ce soit aussi le cas sur la page d'accueil.
