### ISSUE TITLE
Faire une déclaration d'accessibilité et mettre le lien sur la page accessibilité

### ISSUE THREAD

**Issue by Aurelie-Jallut** [umap-project/umap-dsfr#26]
- [ ] Faire une déclaration d'accessibilité : qu'on peut générer via ce générateur : https://betagouv.github.io/a11y-generateur-declaration/#create
- [ ] Ajouter lien vers la déclaration sur [cette page accessibilité](https://umap.incubateur.anct.gouv.fr/contents/mentions-legales/#accessibilite)

**Comment by Aurelie-Jallut** [comment]
et Il faudrait faire pareil pour l'instance OSM : )

**Comment by Aurelie-Jallut** [comment]
PR pour review pour l'instance agents publics : https://github.com/umap-project/umap-dsfr/compare/main...Aurelie-Jallut-patch-1?quick_pull=1

**Comment by davidbgk** [comment]
Fait via https://github.com/umap-project/umap-dsfr/commit/36e948c0c6a38f75a58af82f822d4b1958143d2b + https://github.com/umap-project/umap-dsfr/commit/5bf91489f8ee4ba3c9ae96ef7530a324e5a7f9cc
