### ISSUE TITLE
Change contact email

### ISSUE THREAD

**Issue by virgile-dev** [umap-project/umap-dsfr#6]
@davidbgk we are setting up a ticketing system (Zammad) and had to create a dedicated email umap@anct.beta.gouv.fr because ANCT emails cannot expose an IMAP / POP config for these kind of tools.

We will keep using contact-umap@anct.gouv.fr for sending newsletters and as a contact email but for support ticket we'd like to use : umap@anct.beta.gouv.fr

Can we change the email at the bottom of the landing page ? 
![Capture d’écran du 2024-05-17 11-06-24](https://github.com/umap-project/umap-dsfr/assets/11473995/37847f68-2f4d-4c85-8b4b-89ab205d72e2)

I'd like to use this issue as an opportunity to also discuss how best we could make this contact channel more visible to our users. 
I thought of a couple ways we could do that :
- Add a menu item to the `nav-list` "Support" with mailto:umap@anct.beta.gouv.fr
- Make [this section](https://github.com/umap-project/umap-dsfr/assets/11473995/efabff67-c49e-4787-94e8-e88cb763bbce) part of the footer that it displays on the rest of the pages
- In the map editor add 2 buttons on the help pop-up for the user to find the user doc and the support email easily
![Capture d’écran du 2024-05-17 11-07-29](https://github.com/umap-project/umap-dsfr/assets/11473995/d15b8ca7-5439-4758-8995-e695757fe321)

**Comment by davidbgk** [comment]
Done for the first part (dedicated email in footer).

Can you declare a dedicated issue for the second part which is more a discussion?

**Comment by virgile-dev** [comment]
Sure

**Comment by virgile-dev** [comment]
There you go : https://github.com/umap-project/umap-dsfr/issues/8
