### ISSUE TITLE
Feature maps on the homepage instead of displaying the last created

### ISSUE THREAD

**Issue by virgile-dev** [umap-project/umap-dsfr#9]
More than often the maps I see on the uMap ANCT landing are test maps. 
![Capture d’écran du 2024-05-20 16-26-15](https://github.com/umap-project/umap-dsfr/assets/11473995/e2586f79-d9e7-4a70-8dfc-aa35f98067d1)
I think we discussed featuring a few maps curated by the team that are well executed and show a bunch of different use cases.
Admins could chose the maps to feature from the django back end. 
If more than three are selected only the 3 most recently created display.
What do you think ?

**Comment by yohanboniface** [comment]
C'est possible, il faut mettre ce settings: `UMAP_HOME_FEED="highlighted"` et redéployer.

Ensuite la home affichera les trois dernières cartes modifiées parmi les cartes mises en favoris par les membres du staff.

**Comment by virgile-dev** [comment]
Super ! Vous me direz quand c'est redéployé

**Comment by davidbgk** [comment]
Qui s'occupe (s'est occupé ?) de sélectionner des cartes ?

**Comment by virgile-dev** [comment]
De ce que je comprends c'est les favoris de l'équipe, on devrait être bien
Moi (12) https://umap.incubateur.anct.gouv.fr/fr/user/44/stars/
Yohan (1) https://umap.incubateur.anct.gouv.fr/fr/user/1/stars/
Sophie (1) https://umap.incubateur.anct.gouv.fr/fr/user/45/stars/
Aurelie (5) https://umap.incubateur.anct.gouv.fr/fr/user/37/stars/

**Comment by davidbgk** [comment]
✅ Done!

**Comment by virgile-dev** [comment]
Merci !
